### ISSUE TITLE
Docker issue and Update issue V2

### ISSUE THREAD

**Issue by tombomb** [causefx/Organizr#1050]
###### Operating System: Docker
<hr>

##### Problem Description:

The "Update Available" message only takes you to the update tab if you are on the system settings tab.  It updates the bread crumbs in the top right but doesn't switch over to it. (I dont think this is related to docker)

Another little side issue that is probably an error with me is when I update its reverted on the container restarting, is there something I should put in my docker file to stop it from reverting like adding another volume? I am kinda new to docker.
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
what docker image?

**Comment by tombomb** [comment]
organizrtools/organizr-v2
from
https://hub.docker.com/r/organizrtools/organizr-v2
am i not using the right one?

My docker-compose is:
```
  organizrv2:
    container_name: organizrv2
    restart: always
    image: organizrtools/organizr-v2
    volumes:
      - ${USERDIR}/docker/organizrv2:/config
      - ${USERDIR}/docker/shared:/shared
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "9010:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
```
