### ISSUE TITLE
rTorrent different endpoints 

### ISSUE THREAD

**Issue by tombomb** [causefx/Organizr#1072]
###### Operating System: docker
<hr>

##### Problem Description:

rTorrent with a diffrent end point not ending in .php
<hr>

##### Reproduction Steps:

Use a different end point that is not /RPC2 or end in .php I temp fixed by commenting out
https://github.com/causefx/Organizr/blob/v2-master/api/functions/homepage-connect-functions.php#L798
and making the url be 
https://domain/xmlrpc

maybe have a box to put in the endpoint
<hr>

#### Errors on screen?  If so paste here:

```
```

**Comment by causefx** [comment]
if you have dev you can test that out

**Comment by tombomb** [comment]
im on docker so i cant just switch over to dev to test it, but i manualy replaced the 3 files and could not get it to work, 

tried 
```
url = https://sub.doman.ca
rTorrentURLOverride = /xmlrpc
```
```
url = https://sub.doman.ca
rTorrentURLOverride = xmlrpc
```
```
url = https://sub.doman.ca/xmlrpc
rTorrentURLOverride = 
```
```
url = https://sub.doman.ca/
rTorrentURLOverride = xmlrpc
```
```
url = https://sub.doman.ca/
rTorrentURLOverride = /xmlrpc
```
```
url = https://sub.doman.ca/xmlrpc
rTorrentURLOverride = /xmlrpc
```

one thing i saw was 
https://github.com/causefx/Organizr/blob/9dda0a76337e31ce6f8c4d9b9a40edfe4cadc74b/api/functions/homepage-connect-functions.php#L799
it looks like ``$extraPath`` never gets set to ``$GLOBALS['rTorrentURLOverride']`` though its been a while since i messed with php and have never used the short hand for if statements. I did try setting 799 = ```$extraPath = (empty($GLOBALS['rTorrentURLOverride'])) ? $extraPath : $GLOBALS['rTorrentURLOverride'];``` and trying all above but still no dice

not sure if im just failing some where or not, please let me know what to smack next =p

**Comment by tombomb** [comment]
ok wicked strange, i think there is an issue in the testing of the api. with my change of 
```
$extraPath = (empty($GLOBALS['rTorrentURLOverride'])) ? $extraPath : $GLOBALS['rTorrentURLOverride'];
```
the api tells me it fails but then on the actual page, it loads just fine with my settings configured as

```
url = https://sub.doman.ca
rTorrentURLOverride = /xmlrpc
```

**Comment by causefx** [comment]
sorry. the override is for the full url. i didn’t work on test api yet since i wanted to see if this worked. which image on docker are u using?

**Comment by causefx** [comment]
this change should be able to check any url inputed.

**Comment by tombomb** [comment]
this is my docker-compose for organizrv2

```
  organizrv2:
    container_name: organizrv2
    restart: always
    image: organizrtools/organizr-v2
    volumes:
      - ${USERDIR}/docker/organizrv2:/config
      - ${USERDIR}/docker/shared:/shared
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "9000:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
```

Just loaded in the last changes you did and it worked perfectly
