### ISSUE TITLE
How to keep sidebar menu visible

### ISSUE THREAD

**Issue by daledude** [causefx/Organizr#1242]
Is there some css or javascript I can use to keep the sidebar menu open? I prefer that it constantly be expanded.

**Comment by HalianElf** [comment]
Yea, throw this in the custom CSS. You can thank @leram84
```css
@media only screen and (min-width: 768px) {
    .sidebar,
    .sidebar .sidebar-head {
        width: 70px !important;
    }
    .sidebar-head {
        padding: 4px 26px !important;
    }
    #side-menu .fa-fw {
        width: 50px !important;
        font-size: 40px;
    }
    #side-menu>li>a {
        padding-left: 10px;
        padding-bottom: 5px;
        padding-top: 5px;
        display: block;
    }
    .sidebar .hide-menu {
        display: none !important;
    }
    .sidebar:hover {
        box-shadow: none;
    }
    #page-wrapper {
        margin-left: 70px;
    }
    .sidebar .nav-second-level li a,
    .sidebar:hover .nav-second-level li a {
        padding: 5px 10px;
    }
}
```

**Comment by daledude** [comment]
Unfortunately, that doesn't seem to work. I'm using v2.0.307 with the Organizr Dark theme and after putting that code in custom CSS it just makes the icons bigger. The sidebar doesn't slide out anymore.

Thanks for taking the time to share tho.

**Comment by HalianElf** [comment]
Sorry, grabbed the wrong one.
```css
@media only screen and (min-width: 768px) {
    .sidebar,
    .sidebar .sidebar-head {
        width: 240px;
    }
    .sidebar .hide-menu {
        display: inline;
    }
    .sidebar .nav-second-level li a {
        padding-left: 30px;
    }
    #page-wrapper {
        margin: 0 0 0 240px;
    }
    .container-fluid {
    padding-left: 25px;
    }
    .navbar-header {
    padding-left: 185px;
    }
}
```

**Comment by daledude** [comment]
That works. Thanks again @HalianElf for taking the time.

**Comment by IamCage** [comment]
> Sorry, grabbed the wrong one.
> 
> ```css
> @media only screen and (min-width: 768px) {
>     .sidebar,
>     .sidebar .sidebar-head {
>         width: 240px;
>     }
>     .sidebar .hide-menu {
>         display: inline;
>     }
>     .sidebar .nav-second-level li a {
>         padding-left: 30px;
>     }
>     #page-wrapper {
>         margin: 0 0 0 240px;
>     }
>     .container-fluid {
>     padding-left: 25px;
>     }
>     .navbar-header {
>     padding-left: 185px;
>     }
> }
> ```

thank you. working perfect :)

**Comment by sn4901** [comment]
The above seemed to get cut off on the right for me. I found this to work better at least on my Organizr.

```css
@media only screen and (min-width: 768px) {
    .sidebar,
    .sidebar .sidebar-head {
        width: 240px;
    }
    .sidebar .hide-menu {
        display: inline;
    }
    .sidebar .nav-second-level li a {
        padding-left: 30px;
    }
    #page-wrapper {
        margin: 0;
        left: 240px;
        width: calc(100% - 240px);
    }
    .container-fluid {
    padding-left: 25px;
    }
    .navbar-header {
    padding-left: 185px;
    }
}
```
