### ISSUE TITLE
custom css question

### ISSUE THREAD

**Issue by Nosirus** [causefx/Organizr#1300]
and is it possible with a custom css to remove github and disweb.deploys.io button ?

I'm also looking to move the top bar and integrate it on the sidebar.

**Comment by GilbN** [comment]
check https://github.com/Archmonger/Blackberry-Themes/wiki/Installation-Instructions#organizr-minimal-edition-remove-top-navbar

and 

```css
/*Hide Sign Out, Github and Support buttons in nav*/

#side-menu>.devider, .nav #github, .nav #menu-Organizr-Support{
    display: none;
}
```

**Comment by Nosirus** [comment]
Oh just perfect ! Thank you very much, fast and efficient :)

I'm going to study this page! 
can we modify the iframe css with organizr too?

**Comment by GilbN** [comment]
Yes. 
```css
.frame-Duplicati {background-color: white}
```
Duplicati is the name of the Tab

**Comment by Nosirus** [comment]
thx, last question, is there a possibility to add the closing crosses on the sides?

**Comment by causefx** [comment]
not sure whatcha mean

**Comment by Sledgehamma** [comment]
> check https://github.com/Archmonger/Blackberry-Themes/wiki/Installation-Instructions#organizr-minimal-edition-remove-top-navbar
> 
> and
> 
> ```css
> /*Hide Sign Out, Github and Support buttons in nav*/
> 
> #side-menu>.devider, .nav #github, .nav #menu-Organizr-Support{
>     display: none;
> }
> ```

It still shows the sign out button for me. I just added `.nav #sign-out` and it works.

So it looks like:

```css
/*Hide` Sign Out, Github and Support buttons in nav*/

#side-menu>.devider, .nav #github, .nav #menu-Organizr-Support, .nav #sign-out{
    display: none;
}
```
