### ISSUE TITLE
A change in #1565 appears to cause an unhealthy docker container and 404 from the web interface

### ISSUE THREAD

**Issue by maxfield-allison** [causefx/Organizr#1566]
###### Reverse Proxy: Traefik v2
<hr>

##### Problem Description:
After the merge of #1565, The docker container becomes available for a short time once it is spun up but after a short period, accessing the FQDN returns 404. Restarting the container does nothing for access but removing non-persistent volumes and running compose once more will allow access again for a short time.

<hr>

##### Reproduction Steps:
Docker-compose.yml
```
version: "3.7"
services:
######### FRONTENDS ##########

  organizr:
    container_name: organizr
    restart: always
    image: organizr/organizr
    volumes:
      - ${USERDIR}/docker/production/dashboard/organizr:/config
      - ${USERDIR}/docker/production/shared:/shared
#    ports:
#      - "XXXX:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.organizr-rtr.entrypoints=https"
      - "traefik.http.routers.organizr-rtr.rule=Host(`$DOMAINNAME`,`www.$DOMAINNAME`)" 
      - "traefik.http.routers.organizr-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.organizr-rtr.middlewares=chain-no-auth@file" 
      ## HTTP Services
      - "traefik.http.routers.organizr-rtr.service=organizr-svc"
      - "traefik.http.services.organizr-svc.loadbalancer.server.port=80"

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge
```

<hr>

#### Errors on screen?  If so paste here:

No visible errors reported except the 404 
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.


[s6-init] ensuring user provided files have correct perms...exited 0.


[fix-attrs.d] applying ownership & permissions fixes...


[fix-attrs.d] done.


[cont-init.d] executing container initialization scripts...


[cont-init.d] 10-adduser: executing... 




-------------------------------------


GID/UID


-------------------------------------


User uid:    1000


User gid:    1000


-------------------------------------




[cont-init.d] 10-adduser: exited 0.


[cont-init.d] 20-config: executing... 


[cont-init.d] 20-config: exited 0.


[cont-init.d] 30-setup: executing... 


[cont-init.d] 30-setup: exited 0.


[cont-init.d] 35-fpm: executing... 


[cont-init.d] 35-fpm: exited 0.


[cont-init.d] 40-install: executing... 


-----------------------


|  Updating Organizr  |


-----------------------


HEAD is now at 02cccdc9 Merge pull request #1565 from causefx/v2-develop


Your branch is up to date with 'origin/v2-master'.


Already on 'v2-master'


HEAD is now at 02cccdc9 Merge pull request #1565 from causefx/v2-develop


Already up to date.


[cont-init.d] 40-install: exited 0.


[cont-init.d] 50-debug: executing... 


-----------------------


|     Kernel Info     |


-----------------------


Linux 8d5d86e16d72 5.10.9-051009-lowlatency #202101191835 SMP PREEMPT Tue Jan 19 19:21:12 UTC 2021 x86_64 GNU/Linux


Time Zone: America/Chicago


[cont-init.d] 50-debug: exited 0.


[cont-init.d] done.


[services.d] starting services


[services.d] done.
```
