### ISSUE TITLE
Ombi Homepage widget not working with new v4 branch

### ISSUE THREAD

**Issue by bxlouis** [causefx/Organizr#1572]
###### Operating System: Docker v18.09.8 on DSM 6.6.2.3-25426 Update 3
<hr>

##### Problem Description:
Ombi switched from "v4-preview" to "development" tag in late January on the linuxserver/ombi repo.
v4-preview used to work with the Homepage widget. 
Now that I switched over to "development", the widget remains empty on the homepage, although I get a "API Connection Success" message when testing it from the settings.

I tried to remove and reconfigure the widget without any succes.
Ombi works as usual with the new tag. 

<hr>

**Comment by wglynn01** [comment]
edit: nginx 1.18.0

**Comment by bxlouis** [comment]
Just commenting so that the issue is not closed automatically.

**Comment by waiterr** [comment]
Any news on this? 
This is a cool feature that was lost after v4 :(

**Comment by bxlouis** [comment]
@causefx anything we could do to fix this? 
This is a cool feature that was lost after v4 :(

**Comment by causefx** [comment]
what is the full version for omni?

**Comment by bxlouis** [comment]
4.0.1463

**Comment by causefx** [comment]
I'm currently on `4.0.1430` and my homepage item work fine...

![image](https://user-images.githubusercontent.com/16184466/129231033-090b0c6e-6ef2-42cd-8774-b212f25ee9f3.png)
![image](https://user-images.githubusercontent.com/16184466/129231135-4c261040-8d51-436f-88f4-238da37e3d3e.png)

**Comment by bxlouis** [comment]
Is it running on docker? I tried to delete the config and setup again. The test gives me a "connected" feedback but the plugin remains empty...

**Comment by bxlouis** [comment]
![image](https://user-images.githubusercontent.com/4128333/129231630-87d32f9e-67fb-4e2f-a530-2c756ed5da16.png)

**Comment by bxlouis** [comment]
I don't have any fallback configured. What should you set there?

**Comment by causefx** [comment]
the fallback is only for requesting.  

the image I am using:
```
    ombi:
        container_name: ombi
        hostname: ombi
        image: linuxserver/ombi
        restart: unless-stopped
        volumes:
            - ${DATADIR}/ombi/config:/config
        ports:
            - ${OMBI_PORT_3579}:3579
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        logging:
            driver: json-file
            options:
                max-file: ${DOCKERLOGGING_MAXFILE}
                max-size: ${DOCKERLOGGING_MAXSIZE}
```
