### ISSUE TITLE
Docker Organizr (v2.1.120) shows update is available but not updating since Dec '20?

### ISSUE THREAD

**Issue by wivaku** [causefx/Organizr#1654]
Using Docker Organizr (v2.1.120).
For months the shows a popup about an update, but I am unable to update.

When I click compare it shows the differences since Dec 15 2020:
https://github.com/causefx/Organizr/compare/de49712860211d826e8eb9d033362cc557833f4d...d32ccc94917a5c880f5fcef6d6d5531b62bdf40c

I would assume the update is done by updating the Docker container,  
so tried `docker compose down` and `up` and tried switching from `master` to `dev`.
When I press the update button in the web interface the downloading popup stays at 20%.

![image](https://user-images.githubusercontent.com/2084872/119112231-2d81c380-ba24-11eb-9c0a-a1c85fb0d4d0.png)

My docker-compose.yaml:
```
  organizr:
    container_name: organizr
    restart: unless-stopped
    #image: linuxserver/organizr # previously I used the linuxserver image, which is deprecated
    image: organizr/organizr
    volumes:
      - ${CONFIG}/organizr:/config
    ports:
      - "8800:80"
    environment:
      - branch=master # also tried dev
      - PGID=${GID}
      - PUID=${UID}
      - TZ=Europe/Paris
```
