### ISSUE TITLE
Image Upload doesn't work

### ISSUE THREAD

**Issue by pestspae** [causefx/Organizr#1809]
###### Operating System: Docker on Rocky Linux 8
<hr>

##### Problem Description:

If I try to upload new Images/Icons via the Image Manager in the Organizr settings they don't get uploaded. Organizr reports that the Image was uploaded successfully, yet it is never shown in the overview. I ended up copying the images directly into "/config/www/organizr/plugins/images/tabs/" with rsync.

I deployed Organizr with Docker Compose. The data volume is an NFS volume:
```
version: '3.8'

services:
  organizr:
    image: ghcr.io/organizr/organizr
    container_name: organizr
    volumes:
      - data:/config
    ports:
      - 127.0.0.1:5000:80
    environment:
      - PGID=2000
      - PUID=2000
      - TZ=Europe/Berlin
    restart: "no"

volumes:
  data:
    driver_opts:
      type: nfs
      o: addr=xxx.xxx.xxx.xxx,rw,noatime,rsize=8192,wsize=8192,tcp,soft,timeo=14,nolock
      device: :/path/to/nfs/share
```
Nginx is used as a Reverse Proxy on the Host:
```
server {
    listen                  443 ssl;
    server_name             home.example.com;

    # (I) SSL
    ssl_certificate /path/to/ssl/cert;
    ssl_certificate_key /path/to/key;
    
    location / {
        proxy_pass      http://localhost:5000;
        }
}

# HTTP redirect
server {
    listen      80;
    server_name home.example.com;

    location / {
        return 301 https://home.example.com;
    }
}
```
<hr>

**Comment by tronyx** [comment]
Do the images show in the actual volume after it says it is successful? SQLite doesn't like working with remote store, IE: NFS, so I would suggest trying it with a local volume (as it does not take up all that much space) and see if the issue still happens. Cause is working on using other DB backends with Org, but nothing is ready for production yet.

**Comment by pestspae** [comment]
The images don't show up in the actual volume.
I spawned another container with a local filesystem bind. This time I also didn't use a Reverse Proxy.
```
version: '3.8'

services:
  organizr-test:
    image: ghcr.io/organizr/organizr
    container_name: organizr-test
    volumes:
      - /tmp/organizer-test:/config
    ports:
      - 12345:80
    environment:
      - PGID=2000
      - PUID=2000
      - TZ=Europe/Berlin
    restart: "no"
```
I tried to upload the PNGs via Firefox and Chromium on a Debian 11 Machine. The issue sadly persists.
