### ISSUE TITLE
Organizr + Traefik 2.9 = Bad Gateway

### ISSUE THREAD

**Issue by Gajotres** [causefx/Organizr#1886]
Organizr Version: 2.1.2370
Branch: v2-master
WebServer: nginx/1.20.2
Operating System: Docker on Synology NAS (DS1621+)

<hr>

##### Problem Description:

Hi everyone,

I'm trying to run Organizr Docker behind Traefik reverse proxy and I'm getting "**Bad Gateway caused by: dial tcp 192.168.48.8:6789: connect: connection refused**" error.

Flow: **External Domain** -> (port 443) **Router** ( port 447) -> **Synology NAS Firewall** -> (port 447) **Traefik** (port 443) -> **Organizr** (I'm making port 443 conversation to 447 due to ports 80 and 443 being used by Synology reverse proxy and there's no simple way to turn it off)

Looking at the logs, Traefik is blocking the flow (I cannot see anything in the Organizr logs), but I do not understand why.

I have six other services which are working without issues, and I know this flow should work as it was working with built-in Synology reverse proxy. 

##### Background.

I'm running a dynamic DNS setup via CloudFlare where I'm also managing my domain.

Due to Synology NAS Reverse Proxy limitations, I switched to Traefik 2.9 where I'm running six other services without any issues. Unfortunately, I cannot expose Organizr due to a Bad Gateway issue.

- Communication works over HTTPS and Traefik is successfully handling certificate creation.
- Both Organizr and Traefik are running in the same network segment.
- Turning Synology Firewall off/on makes no difference
- Having an external subdomain proxied on/off on CloudFlare makes no difference. Also, Cloudflare domain development mode on/off makes no difference.
- CloudFlare is not the issue as I've got the same error when accessing Organizr from a different domain (hosted by no-ip).

This is the docker-compose setup I'm currently running:

```version: "3.6"
services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    hostname: traefik    
    ports:
      - "87:80" # Synology reverse proxy is using port 80
      - "447:443" # Synology reverse proxy is using port 443
      # (Optional) Expose Dashboard
      - "8187:8080"  # Don't do this in production!
    volumes:
      - /volume2/Volume2/Config/Traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  organizr:
    container_name: organizr-organizr2
    hostname: organizr-organizr2
    image: organizr/organizr:latest
    restart: unless-stopped
    ports:
      - 6789:80
    volumes:
      - /volume2/Volume2/Config/Organizr2:/config
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Vienna
      - fpm=true
      - branch=v2-master
    labels:  
      - "traefik.enable=true"
      - "traefik.http.routers.organizr2.rule=Host(`organizr2.domain.com`)"
      - "traefik.http.routers.organizr2.entrypoints=web, websecure"
      - "traefik.http.routers.organizr2.tls.certresolver=production"
      - "traefik.http.services.organizr2.loadbalancer.server.port=6789" 

    networks:
      - web
    depends_on:
      - traefik      

networks:
  web:
    name: traefik_web
```

**My Traefik static configuration:**

```
global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# (Optional) Log information
# ---
log:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common  # common, json, logfmt
  filePath: /etc/traefik/traefik.log

# (Optional) Accesslog
# ---
accesslog:
  format: common  # common, json, logfmt
  filePath: /etc/traefik/access.log

# (Optional) Enable API and Dashboard
# ---
api:
  dashboard: false  # true by default
  insecure: false  # Don't do this in production!

# Entry Points configuration
# ---
entryPoints:

  web:
    address: :80
    # (Optional) Redirect to HTTPS
    # ---
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

# Configure your CertificateResolver here...
# ---
certificatesResolvers:
   staging:
     acme:
       email: someemail@gmail.com
       storage: /etc/traefik/acme-dev.json
       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
       httpChallenge:
         entryPoint: web

   production:
     acme:
       email: someemail@gmail.com
       storage: /etc/traefik/acme.json
       caServer: "https://acme-v02.api.letsencrypt.org/directory"
       httpChallenge:
         entryPoint: web

providers:
  docker:
    exposedByDefault: false  # Default is true
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik
    watch: false
```

#### Errors:

```
time="2022-10-19T10:17:28Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"OmitHost\":false,\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"hr,en-GB;q=0.9,en;q=0.8,en-US;q=0.7\"],\"Cache-Control\":[\"max-age=0\"],\"Dnt\":[\"1\"],\"Sec-Ch-Ua\":[\"\\\"Chromium\\\";v=\\\"106\\\", \\\"Microsoft Edge\\\";v=\\\"106\\\", \\\"Not;A=Brand\\\";v=\\\"99\\\"\"],\"Sec-Ch-Ua-Mobile\":[\"?0\"],\"Sec-Ch-Ua-Platform\":[\"\\\"macOS\\\"\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47\"],\"X-Forwarded-Host\":[\"organizr2.domain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik\"],\"X-Real-Ip\":[\"192.168.48.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"organizr2.domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.48.1:57506\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2022-10-19T10:17:28Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"OmitHost\":false,\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"hr,en-GB;q=0.9,en;q=0.8,en-US;q=0.7\"],\"Cache-Control\":[\"max-age=0\"],\"Dnt\":[\"1\"],\"Sec-Ch-Ua\":[\"\\\"Chromium\\\";v=\\\"106\\\", \\\"Microsoft Edge\\\";v=\\\"106\\\", \\\"Not;A=Brand\\\";v=\\\"99\\\"\"],\"Sec-Ch-Ua-Mobile\":[\"?0\"],\"Sec-Ch-Ua-Platform\":[\"\\\"macOS\\\"\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47\"],\"X-Forwarded-Host\":[\"organizr2.domain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik\"],\"X-Real-Ip\":[\"192.168.48.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"organizr2.domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.48.1:57506\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://192.168.48.8:6789"
time="2022-10-19T10:17:28Z" level=debug msg="'502 Bad Gateway' caused by: dial tcp 192.168.48.8:6789: connect: connection refused"
time="2022-10-19T10:17:28Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"OmitHost\":false,\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"hr,en-GB;q=0.9,en;q=0.8,en-US;q=0.7\"],\"Cache-Control\":[\"max-age=0\"],\"Dnt\":[\"1\"],\"Sec-Ch-Ua\":[\"\\\"Chromium\\\";v=\\\"106\\\", \\\"Microsoft Edge\\\";v=\\\"106\\\", \\\"Not;A=Brand\\\";v=\\\"99\\\"\"],\"Sec-Ch-Ua-Mobile\":[\"?0\"],\"Sec-Ch-Ua-Platform\":[\"\\\"macOS\\\"\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47\"],\"X-Forwarded-Host\":[\"organizr2.domain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik\"],\"X-Real-Ip\":[\"192.168.48.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"organizr2.domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.48.1:57506\",\"RequestURI\":\"/\",\"TLS\":null}"

```
